### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by mimi89999** [LibreSignal/LibreSignal#4]

**Comment by SecUpwN** [comment]
Whoo-hooo, I'm all in for making **your** fork the official `LibreSignal` project! :+1:

But before diving right into it: Please _definitely_ make sure that the _experimental_ repository `https://eutopia.cz/experimental/fdroid/repo/` (which had to be added to F-Droid on your Android in order to make `LibreSignal` appear) gets into your posession - or, even better, transferred into the official F-Droid builds. That way, you'll ensure a much larger user base and for sure more developers. I guess it will be necessary clearing things up with whoever owns that link. But _very_ important in my eyes.

Furthermore, I am in closer connection to Mike Kuketz from the largest German IT-Security blog, who already published a German article about `LibreSignal` a while ago. You may read it at [Android: Signal ohne Google Cloud Messaging](https://www.kuketz-blog.de/?s=LibreSignal) if you are able to read German. I've already talked to him about the proposal to move into an official organization (which you've already done here) and he told he that he would love to hear from me how things are moving forward so that he can update his article (positive side-effect: even more people will star your repo and join development on your new organization here).

So let's do this! What would you like me to change in your current `README`? I'll craft a pull request then.

**Comment by mimi89999** [comment]
In README I would like to give some basic informations about LibreSignal, change the name and correct issue and wiki links to point to the pages in this repo.

**Comment by ghost** [comment]
Please don't link to http://support.whispersystems.org/ for support. Offloading support to them will just make an unpleasant experience for all, OWS, you, the users (and most likely fdroid...).

**Comment by mimi89999** [comment]
I will edit the README tomorrow.

**Comment by SecUpwN** [comment]
I'm currently on the first basic edits. Stay tuned for my pull request in 30 minutes.

**Comment by mimi89999** [comment]
@krt16s The README is changed.
