### ISSUE TITLE
Test before publishing on F-Droid

### ISSUE THREAD

**Issue by mimi89999** [LibreSignal/LibreSignal#5]

**Comment by SecUpwN** [comment]
Quiting myself here to make sure you won't just ignore it (I know you're not that kind of person):

> Please definitely make sure that the experimental repository https://eutopia.cz/experimental/fdroid/repo/ (which had to be added to F-Droid on your Android in order to make LibreSignal appear) gets into your posession - or, even better, transferred into the official F-Droid builds. That way, you'll ensure a much larger user base and for sure more developers. I guess it will be necessary clearing things up with whoever owns that link. But very important in my eyes.

**Comment by mimi89999** [comment]
I would like LibreSignal to be distributed in the official F-Droid repo. The problem is that Signal (and LibreSignal) is using custom maven repos. I don't know where I can find the source of the .jar files in https://github.com/WhisperSystems/maven

**Comment by SecUpwN** [comment]
> I would like LibreSignal to be distributed in the official F-Droid repo.

Yes, me too. But I consider it important that people actually _switch_ to your repository instead of staying on thne old _experimental_ repo, which has to be added manually. But maybe that happens all by itself once `LibreSignal` is on the official F-Droid repo and dsiplays an incompatible update.

> don't know where I can find the source of the .jar files in https://github.com/WhisperSystems/maven

The only guy I know who is tight on his horse regarding .jar and maven, is @larsgrefer. Maybe he knows? I'm sure he'll chime in and answer this question here soon. Patience is the key, he is very busy.

**Comment by mimi89999** [comment]
I can't find smil (https://github.com/WhisperSystems/maven/tree/master/smil/releases/org/w3c/smil) source code.

**Comment by SecUpwN** [comment]
Maybe [their official site](https://www.w3.org/AudioVideo/) is helpful?

**Comment by mimi89999** [comment]
I created an issue to ask about this: https://github.com/WhisperSystems/maven/issues/9

The issue was delated, but it's still visible on my profile: https://github.com/mimi89999

**Comment by mimi89999** [comment]
They also disabled issues for this repo :-(

**Comment by dotlambda** [comment]
Does this help?
https://www.w3.org/TR/1999/WD-smil-boston-dom-19991115/java-binding.html

**Comment by mimi89999** [comment]
I found a newer version: http://search.maven.org/remotecontent?filepath=org/eclipse/birt/runtime/org.w3c.dom.smil/1.0.1.v200903091627/org.w3c.dom.smil-1.0.1.v200903091627-sources.jar

**Comment by mimi89999** [comment]
The version that I found doesn't work.

**Comment by mimi89999** [comment]
https://github.com/LibreSignal/LibreSignal/commit/a4237e50b3353bdf12f6fddc3579a2fea20f8a0b
:smile:

**Comment by mimi89999** [comment]
https://github.com/LibreSignal/LibreSignal/commit/02fe5dac3a6efa63c5a3ad9508072167944d8c75
:smile:

**Comment by SecUpwN** [comment]
Thanks for your continued effort to really make `LibreSignal` a _really_ free app, @mimi89999! I wonder what is wrong with OpenWhisperSystems that they're radically deleting Issues and not even replying. @mimi89999, please add an Icon to the `LibreSignal` organization. That alone makes users follow your repositiries much more. I know since I am a very eye-balling person myself, see my own repositories.

**Comment by mimi89999** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/1278
:smile:

**Comment by SecUpwN** [comment]
> https://gitlab.com/fdroid/fdroiddata/merge_requests/1278

Wonderful! Will that officially replace the experimental https://eutopia.cz/experimental/fdroid/repo/?

**Comment by mimi89999** [comment]
The Eutopia repo belongs to @xmikos . I don't know which version he will want to distribute in his repo.

**Comment by SecUpwN** [comment]
> The Eutopia repo belongs to @xmikos . I don't know which version he will want to distribute in his repo.

It would be very lovely if @xmikos would support the move to your official new repo for `LibreSignal`!

**Comment by mimi89999** [comment]
I haven't found any issues in LibreSignal other than https://github.com/JavaJens/TextSecure/issues/54
